### ISSUE TITLE
Fix project name

### ISSUE THREAD

**Issue by metenn** [Natchuz/wmoon#1]
The project title is mysoginist, sexist, offensive, and quite frankly, shit.
I propose to rename it to the title "wmypierdalaj".
![f2b8a8f](https://user-images.githubusercontent.com/49620905/145444413-70d7f70c-ab29-4ba4-b5df-171a2209a786.jpg)

**Comment by Matdas12** [comment]
is it "wmypierdalaj" or "w*pierdalaj"

**Comment by MasloMaslane** [comment]
![77236510-47F7-4AAD-B18F-4F42C80C0872](https://user-images.githubusercontent.com/22548407/145533490-a944089e-f8de-4fbf-9142-be733db2e2fe.jpeg)
I agree z przedmówcą
